# pre-class 
### Question 1:

Using a loop, print the integers from 1 to 50. 

for(i in 1:50){
  print(i)
}


### Question 2:

### A.  Using a loop, add all the integers between 0 and 1000.


sum_1=0
for(i in 0:1000){
  sum_1 <- sum_1 + i
}
print(sum_1)

#### B. Now, add all the EVEN integers between 0 and 1000 (hint: use seq())
sum_1=0
for(i in 0:1000){
  if(i%%2==0){
  sum_1 <- sum_1 + i
  }
}
print(sum_1)

### C. Now, repeat A and B WITHOUT using a loop.
print(1:50)
sum(0:1000)


### Question 3:

### Here is a dataframe of survey data containing 5 questions :

#### A. Using a loop, create a new dataframe called survey.clean where all the invalid values (those that are not integers between 1 and 5) are set to NA.
survey <- data.frame(
  "participant" = c(1, 2, 3, 4, 5, 6),
  "q1" = c(5, 3, 2, 7, 11, 0),
  "q2" = c(4, 2, 2, 5, -10, 99),
  "q3" = c(-4, -3, 4, 2, 9, 10),
  "q4" = c(-30, 5, 2, 23, 4, 2),
  "q5" = c(88, 4, -20, 2, 4, 2)
)
survey.clean <- survey 
for(i in 1:6){
   for(j in 2:6){
    if(survey.clean[i,j]<0 | survey.clean[i,j]>5 ){
      survey.clean[i,j] = NA
    }
   }
}
### B. Now, again using a loop, add a new column to the dataframe called “invalid.answers” that indicates, for each participant, how many bad answers they gave.
survey.clean
invalid.answers <- rep(0, 6)
invalid.answers
for(i in 1:6){
  for(j in 2:6){
    if (is.na(survey.clean[i,j])){
      invalid.answers[i] <- invalid.answers[i] + 1
    }
  }
}
survey.clean <- cbind(survey.clean,invalid.answers)
print(survey.clean)
