install.packages("gapminder")
library(dplyr)
library(gapminder)
gapminder

# 1.How many unique countries are represented per continent?

gapminder%>%
  group_by(continent) %>% 
  summarize(n_distinct(country))

# 2.Which European nation had the lowest GDP per capita in 1997?

gapminder%>%
  filter(continent == "Europe",year == 1997)%>%
  arrange(gdpPercap)%>%
  head(1)
  
#3.According to the data available, what was the average life expectancy across each continent in the 1980s?
gapminder%>%
  filter(year == 1982 |year==1987)%>%
  group_by(continent)%>%
  summarize(av_cont_1980 = mean(lifeExp))

#4.What 5 countries have the highest total GDP over all years combined?
gapminder%>%
  group_by(country)%>%
  mutate(Gdp=gdpPercap*pop)%>%
  summarize(total_Gdp=sum(Gdp))%>%
  arrange(desc(total_Gdp))%>%
  head(5)

#5 What countries and years had life expectancies of at least 80 years? N.b. only output the columns of interest: country, life expectancy and year (in that order).
gapminder%>%
  select(country,lifeExp,year)%>%
  filter(lifeExp >=80)

#6 What 10 countries have the strongest correlation (in either direction) between life expectancy and per capita GDP?
gapminder%>%
  group_by(country)%>%
  summarize(cor_1=cor(lifeExp,gdpPercap))%>%
  arrange(desc(abs(cor_1)))%>%
    head(10)

#7 Which combinations of continent (besides Asia) and year have the highest average population across all countries? N.b. your output should include all results sorted by highest average population
gapminder%>%
  filter(continent!="Asia")%>%
  group_by(continent,year)%>%
  summarize(average_pop=mean(pop))%>%
 arrange(desc(average_pop))

  
#8.Which three countries have had the most consistent population estimates (i.e. lowest standard deviation) across the years of available data?
gapminder%>%
  group_by(country)%>%
   summarize(sd_con = sd(pop))%>%
    arrange(sd_con)%>%
     head(3)
  
#9.Subset gm to only include observations from 1992 and store the results as gm1992. What kind of object is this?
gm_1992 <- gapminder%>%
                filter(year==1992)%>%
   gm_1992
  
  #

#10.Which observations indicate that the population of a country has decreased from the previous year and the life expectancy has increased from the previous year? 
gapminder%>%
  arrange(country,year)%>%
  group_by(country)%>%
  filter(pop < lag(pop) & lifeExp > lag(lifeExp))
